/**
 * Created by agradip.sarkar on 14/07/15.
 */

if (Meteor.isClient) {
    Template.basic.helpers({
        "files": function() {
            return S3.collection.find();
        }
    });
    Template.basic.events({
        "click button.upload": function(event,tpl) {
            var cropZone = tpl.imageCropped.plugins.crop.cropZone;
            cropZone.visible = false;
            var dataURL = tpl.imageCropped.canvas.toDataURL({
                left: cropZone.getLeft(),
                top: cropZone.getTop(),
                width: cropZone.getWidth(),
                height: cropZone.getHeight()
            });

            return S3.upload({
                files: [dataURL],
                encoding:'base64',
                path: "image"
            }, function(error, result) {
                if (error) {
                    return console.log("Unable to upload");
                } else {
                    return console.log(result);
                }
            });
        },
        "click button.delete": function(event) {
            return S3["delete"](this.relative_url, (function(_this) {
                return function(error, res) {
                    if (!error) {
                        console.log(res);
                        return S3.collection.remove(_this._id);
                    } else {
                        return console.log(error);
                    }
                };
            })(this));
        }
    });
    Template.basic.rendered = function(){
        var _this  = this;
        this.autorun(function(){
            _this.imageCropped = new Darkroom('.img-to-crop', {
                // Canvas initialization size
                minWidth: 200,
                minHeight: 200,
                maxWidth: 320,
                maxHeight: 480,
                // Plugins options
                plugins: {
                    crop: {
                        minHeight: 80,
                        minWidth: 80,
                        maxHeight: 160,
                        maxWidth: 160,
                        ratio: 1
                    },
                    save: false // disable plugin
                },
                init: function () {
                    var cropPlugin = this.getPlugin('crop');
                    this.addEventListener('crop:update', function () {
                        console.log(arguments, cropPlugin);
                    });

                    this.addEventListener('image:change', function () {
                        console.log(arguments, cropPlugin);
                    });
                    cropPlugin.selectZone(80, 30, 160, 160);
                    //cropPlugin.okButton.hide(true);
                    //cropPlugin.cancelButton.hide(true);
                    //cropPlugin.cropButton.hide(true);
                    //cropPlugin.requireFocus();
                }
            });
        })
    }
}

if (Meteor.isServer) {
    S3.config = {
        key: '<TestKEY>',
        secret: '<TestKEY>',
        bucket: 'muze-qa',
        region:'us-west-2'
    };
}



// ---
// generated by coffee-script 1.9.2
